sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t pathmotion/composer-php-7.2 .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
